services:
  - type: web
    name: verdict-backend
    env: python
    region: ohio
    buildCommand: "pip install -r requirements.txt"
    startCommand: "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
